id: I1F19B797
default_language: es
source: https://www.lotsawahouse.org
initial_creation_type: web_scrap
imported: 2023-01-04 11:28:45.480511
last_modified: 2023-01-04 11:28:45.480527
source_metadata:
  collections:
  - Alak Zenkar Rinpoche
  - Works of Tibetan Masters
bases:
  BA30:
    title: Long Life Prayer for Patrick Gaffney (Yeshé Wangyal)
    base_file: BA30.txt
    order: 1
copyright:
  status: Unknown
  notice: ''
